### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by firashamadi66** [williamswhy/SSLSocket#2]
the source code of the client and server are the same

**Comment by skiunke** [comment]
Still persists. Would be awesome, if the correct version could be pushed.

**Comment by williamswhy** [comment]
Sorry I did not actively maintain this project. In my use case, I needed a duplex communication between my server and client so that's why I put the exact same code in both folders so both of them can sand and listen. But I think you are right, it is a good idea to separate them.
